services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  PinduoduoApiBundle\Command\:
    resource: '../../Command/'
    public: true
  PinduoduoApiBundle\Controller\:
    resource: '../../Controller/'
  PinduoduoApiBundle\MessageHandler\:
    resource: '../../MessageHandler/'
    public: true
  PinduoduoApiBundle\Procedure\:
    resource: '../../Procedure/'
    public: true
  PinduoduoApiBundle\Repository\:
    resource: '../../Repository/'
  PinduoduoApiBundle\Service\:
    resource: '../../Service/'
    public: true
  PinduoduoApiBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true
